### ISSUE TITLE
Integrate clang-format into CI and IDEs

### ISSUE THREAD

**Issue by Metadorius** [Phobos-developers/Phobos#1143]
```[tasklist]
### Tasks
- [ ] Figure out and document/automate the steps to integrate and use clang-format in:
  - [ ] (at least) VS
  - [ ] (hopefully) VSCode
  - [ ] (maybe) CLion (but no one uses it so whatever)
- [ ] Create the rules for clang-format based on our style
- [ ] Write a workflow for CI to check formatting
```
